version: '3.1'

services:
  
  db:
    image: mysql:5.7
    ports:
      - 8083:3306
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - ./db:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin
    #container_name: phpmyadmin
    environment:
      PMA_HOST: db
      PMA_ARBITRARY: 1
    restart: always
    ports:
     - 8081:80
    links:
     - db:db
    volumes:
     - ./phpmyadmin/sessions:/sessions

volumes:
  db:
    name: django_db
  phpmyadmin:
    name: django_phpmyadmin


# file usage:
# docker-compose -f ./Django_servers.yml up -d  // turning on docker compose run it inside .yml file dir
#
# docker-compose -f ./Django_servers.yml down   // turning down docker compose






