version: '3.1'

services:
  
  db:
    image: postgres
    ports:
      - 8083:5432
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  # phpmyadmin:
  #   image: phpmyadmin
  #   #container_name: phpmyadmin
  #   environment:
  #     PMA_HOST: db
  #     PMA_ARBITRARY: 1
  #   restart: always
  #   ports:
  #    - 8081:80
  #   links:
  #    - db:db
  #   volumes:
  #    - ./phpmyadmin/sessions:/sessions

volumes:
  db:
    name: django_db
  # phpmyadmin:
  #   name: django_phpmyadmin


# file usage:
# docker-compose -f ./Django_servers.yml up -d  // turning on docker compose run it inside .yml file dir
#
# docker-compose -f ./Django_servers.yml down   // turning down docker compose






